fix: Add several c8s fixes for missing deps and decorators
neoave/mrack pull request #227
Opened 2022-12-12 12:55 UTC by Tiboris

fix: Add cache decorator for older python versions.
    
    fix(mrack.spec): Missing dependency in c8s for beaker-client

2022-12-12 13:58 UTC, Tiboris commented
c8s run is now green: https://dashboard.packit.dev/results/testing-farm/153647

2022-12-12 13:59 UTC, Tiboris commented
Should I remove temp commits? @pvoborni

2022-12-13 09:41 UTC, pvoborni requested changes
the c8s fixes looks good to me. But I think the smoke test has issues in it (will comment in the other PR).

2022-12-13 10:02 UTC, Tiboris commented
I will remove the 4 commits from other PR then it should be fine do you agree? and I will rebase #226 on top of this one.

2022-12-13 11:33 UTC, merged