Add docs on how to set credentials
neoave/mrack pull request #43
Opened 2020-10-28 19:58 UTC by netoarmando

Quick guide on how set credentials for current supported providers.

Signed-off-by: Armando Neto <abiagion@redhat.com>

2020-10-30 15:23 UTC, pvoborni commented
Did a quick read and it looks good to me. Though I don't say that I followed the instructions so if it is bad then I did not noticed that :).

2020-10-30 15:25 UTC, pvoborni commented
I wonder if we can somehow build the documentation in PRs, so that we can also check if it looks good.

2020-10-30 15:30 UTC, netoarmando commented
> I wonder if we can somehow build the documentation in PRs, so that we can also check if it looks good.

We can, but when I ran `make html` with a typo instead the correct path to `credentials.rst`, the output was helpful to detect the error; however, the return code was always `0`.

2020-10-30 15:36 UTC, pvoborni commented
One thing is pass the build. This should be added to Azure. But I also though, if e.g. read the docs or something else can build the branch so that we can see how it actually looks, e.g. if it is correctly formatted - without a need to check it out locally, build it and see it.

2020-10-30 15:37 UTC, pvoborni commented
In any case, I don't have any problem with merging this PR.

2020-10-30 16:37 UTC, Tiboris requested changes
@netoarmando Thanks for the patch!

There are some nitpicks which may be good to at least look at I do not insist on change but some changes seems to be in place.
My english no perfect but I have 57 to 78 certicates :laughing:  :wink: .

Please have a look on the comments.

2020-10-30 16:37 UTC, Tiboris commented on docs/guides/credentials.rst
> +to original resources you can find more info about that.
```suggestion
to original resources where you can find more info about that.
```

2020-10-30 16:37 UTC, Tiboris commented on docs/guides/credentials.rst
> +The most straightforward way is by using a shared config file. Its default location
```suggestion
The most straightforward way is to use a shared config file. Its default location
```

2020-10-30 16:37 UTC, Tiboris commented on docs/guides/credentials.rst
> +Instructions on where you can file that RC file are available `here <https://docs.openstack.org/mitaka/cli-reference/common/cli_set_environment_variables_using_openstack_rc.html>`__
Did you mean find here?
```suggestion
Instructions on where you can find the RC file are available `here <https://docs.openstack.org/mitaka/cli-reference/common/cli_set_environment_variables_using_openstack_rc.html>`__
```

2020-10-30 16:37 UTC, Tiboris commented on docs/guides/credentials.rst
> +More info about Beaker client configuration available `here <https://beaker-project.org/docs/user-guide/bkr-client.html>`__
```suggestion
More info about Beaker client configuration is available `here <https://beaker-project.org/docs/user-guide/bkr-client.html>`__
```

2020-10-30 16:37 UTC, Tiboris commented on docs/index.rst
> +.. mrack documentation master file, created by
ouch :smile:

2020-10-30 16:37 UTC, Tiboris commented on docs/index.rst
> +provider name without needing to redefine the provider/cloud specifics.
```suggestion
provider name without a need to redefine the provider/cloud specifics.
```

2020-11-03 18:50 UTC, netoarmando commented
@pvoborni @Tiboris I added a basic support to build docs and save them into Azure's artifacts.

2020-11-04 11:32 UTC, Tiboris approved these changes
Thanks @netoarmando !

2020-11-04 12:21 UTC, merged